[tool.poetry]
name = "new"
version = "0.1.0"
description = ""
authors = ["Mian Maaz Ullah Khan <115078151+mmaazkhanhere@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
fastapi = "^0.115.6"
uvicorn = "^0.32.1"
langchain = "^0.3.9"
langgraph = "^0.2.54"
langchain-groq = "^0.2.1"
python-dotenv = "^1.0.1"
langchain-pinecone = "^0.2.0"
langchain-huggingface = "^0.1.2"
langchain-community = "^0.3.9"
python-multipart = "^0.0.19"
ipython = "^8.30.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
